<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>LoLRemote.Simulator</RootNamespace>
    <AssemblyName>LoLRemote.Simulator</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoLRemote.Simulator.Core\LoLRemote.Simulator.Core.csproj" />
  </ItemGroup>

</Project>
